### ISSUE TITLE
Create a site everyone can enjoy!

### ISSUE THREAD

**Issue by EdgeCaseBerg** [the-hobbes/the-hobbes.github.io#1]
You've still got the default jekyll blog post up! Where's your stuff? :D

**Comment by the-hobbes** [comment]
All right all right, first post is up!

https://the-hobbes.github.io/update/protobuf/golang/2015/05/30/golang-protocol-buffers.html

**Comment by EdgeCaseBerg** [comment]
good comments in  that  protobuff code

On Sat, May 30, 2015 at 6:37 PM, Phelan Vendeville <notifications@github.com

> wrote:
> 
> Closed #1 https://github.com/the-hobbes/the-hobbes.github.io/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/the-hobbes/the-hobbes.github.io/issues/1#event-317987226
> .

## 

~Ethan J. Eldridge
http://www.ethanjoachimeldridge.info
Programmer | Computer Scientist
Former UVM CS Crew Executive Triumvirate Member
Former UPE UVM Chapter President
Find my pgp for encrypted messages here on MIT's server
http://pgp.mit.edu/pks/lookup?search=ejayeldridge&op=index
